### ISSUE TITLE
There is no light from searchlight when I place a searchlight in flying mode

### ISSUE THREAD

**Issue by ArianKG** [Lizard-Of-Oz/Searchlight#1]
There is no light from searchlight when I place a searchlight in flying mode.

**Comment by Lizard-Of-Oz** [comment]
A searchlight tries to face the player when it gets placed. If a raycast in the player's direction yields no result, if won't create a Light Source. Right click a Searchlight when there are blocks behind you.

That said, it's something worth considering making more intuitive.
